repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        additional_dependencies: ["ruff"]
      - id: ruff-format
        additional_dependencies: ["ruff"]